name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace secrets in Googles App Engine Deployment File
      uses: 73h/gae-app-yaml-replace-env-variables@v0.3
      env:
          APP_KEY: ${{ secrets.APP_KEY }}
      with:
          app_yaml_path: "app.yaml"

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-dev

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install NPM dependencies
      run: npm ci

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: app.yaml

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
